language: haskell
ghc: 7.8

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kubuntu-backports
        packages:
            - libedit-dev
            - g++-4.9
            - gcc-4.9
            - binutils
            - cmake
            - mono-gmcs

install:
    - git submodule update --init --recursive
    - cd libcaide
    - cabal install --only-dependencies

script:
    - export CXX=g++-4.9
    - export CC=gcc-4.9
    - cabal configure && cabal build && tests/run-tests.sh

notifications:
    email:
        on_success: always
    on_failure: always

